name: J3SurvivalCore
version: 1.20.08.23
main: store.j3studios.plugin.SCore
author: J3Studios
depends: [ItemsAdder,ProtocolLib,LoneLibs]
softdepend: [Vault,PlaceholderAPI,DecentHolograms]
loadbefore: [ItemsAdder,ProtocolLib,LoneLibs]
api-version: 1.19
commands:
    testprote: