name: J3SurvivalCore
version: 1.13.09.23
main: store.j3studios.plugin.SCore
author: J3Studios
depends: [ItemsAdder,ProtocolLib,LoneLibs]
softdepend: [Vault,PlaceholderAPI,DecentHolograms]
loadbefore: [ItemsAdder,ProtocolLib,LoneLibs]
api-version: 1.19
commands:
    testprote:
    gamemode:
        aliases: [gm]
    message:
        aliases: [msg,sendmsg,sendmessage,priv,dm]
    list:
        aliases: [conectados,online]
    feed:
        aliases: [comida,food]
    heal:
        aliases: [vida,regenvida,regenhealth]
    
    
    
    